-- MySQL Script generated by MySQL Workbench
-- Tue Jan  5 14:06:15 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bdCI
-- -----------------------------------------------------
-- CI - Informacion de Clientes.
-- 
-- La base de datos administra la informacion del area de soporte asociada a los clientes.

-- -----------------------------------------------------
-- Schema bdCI
--
-- CI - Informacion de Clientes.
-- 
-- La base de datos administra la informacion del area de soporte asociada a los clientes.
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdCI` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema bdci
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema tecmmzapopan
-- -----------------------------------------------------
USE `bdCI` ;

-- -----------------------------------------------------
-- Table `bdCI`.`tecnologia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdCI`.`tecnologia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idCliente` INT NOT NULL,
  `sonicwall` TINYINT NULL,
  `tecnologia` TINYINT NULL,
  `wireless` TINYINT NULL,
  `telefonia` TINYINT NULL,
  PRIMARY KEY (`id`),
  INDEX `fkCliente_tecnologia_idx` (`idCliente` ASC) VISIBLE,
  CONSTRAINT `fkCliente_tecnologia`
    FOREIGN KEY (`idCliente`)
    REFERENCES `bdCI`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
